version: '3'

services:
    python:
        build:
            context: ./Dockerfiles
            dockerfile: ${PYTHON_DOCKERFILE}
        container_name: ${PYTHON_CONTAINER:-python}
        image: ${PYTHON_DOCKERFILE}
        volumes:
            - ${HOST_SRC}:/var/src
        tty: true
