version: '3'

services:
    python3:
        build:
            context: .
            dockerfile: Dockerfile_python_3.11.1
        image: df_python_3.11.1
        container_name: ${PYTHON3_CONTAINER:-python3}
        volumes:
            - ./src:/var/www
        tty: true
