FROM python:3.11.1

# 2022-12-09 00:33
MAINTAINER zhoukan "xiningbank@gmail.com"

ENV LANG C.UTF-8

RUN echo "alias ll='ls -lh --color=auto'" >> ~/.bashrc
#RUN apt-get update
#RUN apt-get install python3-redis 
RUN pip3 install redis
